apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment-container
        image: saumya11031998/assignment:latest
        ports:
        - containerPort: 9090
