apiVersion: v1
kind: Service
metadata:
  name: assignment-service
spec:
  type: LoadBalancer  # Change to NodePort if you're not using a cloud provider
  selector:
    app: assignment
  ports:
    - protocol: TCP
      port: 80         # The port that will be exposed
      targetPort: 9090 # The port on which your app is running inside the container
